camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName:
  filter:
    create: All tasks
#spring:
#  datasource:
##    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:file:/data/demo
#  h2:
#    console:
#      enabled: true
#      path: /h2
#url for console of database: http://localhost:8085/h2
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true  
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true    
server:
  port: 8085

